import re
import random

# drawing prompts
people = ["Shiver from Splatoon", "Frye from Splatoon", "Big Man from Splatoon", "Pearl from Splatoon", "Marina from Splatoon", "Sans Undertale", "our lord and saviour Jesus Christ", "your OC", "pikachu", "Kirby", "Garfield", "Jon Arbuckle", "Meta Knight", "King Dedede", "Magalor", "Freddy Fazbear", "Barack Obama", "Homer Simpson", "Marge Simpson", "Bibble", "Ron Desantis", "Santa Claus", "Satan", "Queen Elizabeth", "Soinc the hedgehog", "Shadow the hedgehog", "Tails", "Dr. Robotnik", "Michelle from bandori (Misaki)", "Agumon", "Hatsune Miku", "Klonoa", "Tom Nook", "Tracer", "Törbjorn", "Genji", "Minecraft Steve", "Wario", "Waluigi", "Monty Mole", "Mario", "Donkey Kong", "Toad", "Bowser", "Gru from dispicable me", "minion from dispicable me", "a JoJo", "Pac-man", "Alucard", "Pheonix Wright", "Miles Edgeworth", "Spider-Man", "Elsa", "Riku", "Sora", "Mickey Mouse", "Goofy", "Blåhaj", "Djungelskog", "The TBH Creature", "The FR Creature", "Madoka", "Homura", "Mami", "Kyoka", "Sayaka", "Shrek", "Donkey", "Lord Faarquad", "Kyubey", "He-Man", "E.T.", "Hello Kitty", "Miffy", "Pitbull (Mr. Worldwide)", "Trubbish", "Furret", "Shuckle", "Quagsire", "Impadimp", "Pyukumuku", "Magnemite", "Gardevoir", "Barbie", "Twilight Sparkle", "Rainbow Dash", "Godzilla", "The Lorax", "Amogus", "Kermit the Frog", "Pikmin", "Puss in Boots", "Humpty Dumpty", "Link", "Zelda", "Tingle", "Mike Wazowski", "Snoopy", "Spongebob Squarepants", "Squidward", "Patrick Star", "Mort", "a Furby", "Walter White", "Morgana from Persona", "Batman", "Peppino Spaghetti from Pizza Tower"]
situations = ["%p dunking on %p", "%p stuck in a glue trap", "%p fighting %p to the death", "%p crying while eating ice cream from the tub", "%p doing a fortnite dance", "%p transing thier gender", "%p being kidnapped by %p", "%p and %p hitting a blunt together", "%p and %p kissing after both eating the same one long noodle", "%p asking out thier crush %p", "%p eating breakfast", "%p gambling away all thier life savings", "%p crying on the toilet", "%p making fucked up food", "%p sniping god", "%p punting babies while %p begs them to stop", "%p getting arrested", "%p won't shut up about crypto", "%p in the hospital", "%p after they became a biblically accurate angel", "%p starting a cult", "%p getting eaten by a shark", "%p as a serial killer", "%p's unsolicited foot pics", "%p pissing on the moon", "%p getting abducted by aliens", "%p mpreg or as a dominatrix", "%p invading area 51", "%p working at macdonalds talking %p's order", "%p going through an emo phase", "%p but scene", "%p wearing decora", "%p at a pride parade", "%p getting Thanos snapped", "%p as a furry (if they're already furry make them human)", "%p just voted", "%p poledancing", "Weezer blue cover with %p, %p, %p and %p", "%p eating a giant gummy worm in the shower", "%p lost in a corn maze", "%p and %p trapped on a desert island", "%p joins a boyband", "%p as a cat maid", "%p as a my little pony character", "%p turning into a warewolf on the full moon", "%p getting blue shelled by %p right at the finish line", "%p beating %p at video games", "%p as a magical girl", "%p in a hamster cage", "%p trying to hang up a christmas tree", "%p drowned in a swimming pool", "%p being interrogated in court by %p", "%p killed %p", "%p inside a Tamagotchi", "%p getting eaten by Charlotte (Madoka Magicka)", "%p in a wheelchair", "%p dealing drugs to %p", "%p and %p getting married", "%p's JoJo stand", "%p doing a ritual to summon %p", "%p doing thier taxes", "%p exploiting the poor", "%p getting crucified", "%p getting guillotined", "%p getting resuscitated by %p", "%p giving %p mouth to mouth", "%p begging for %p's nudes", "%p getting evicted by %p", "%p's mugshot", "%p behind bars", "%p and %p getting divorced", "Yaasified %p", "%p as a kaiju terrorising a city", "%p riding a Skateboard with a backwards cap and sunglasses", "%p getting bottom surgery at Claire's", "%p wearing a tutu", "%p t-posing over cowering %p", "%p being microwaved", "%p eats a cake and gets revived", "%p becomes a zombie", "%p runs for president", "%p confesses thier sins", "%p gets burned at the stake", "%p's birthday party but the only person who showed up was %p"]

def ReplacePeopleInSituations(inputStr : str):
    
    for found in re.findall("%p", inputStr):

        inputStr = re.sub(found, random.choice(people), inputStr, 1)

    return inputStr

def GenerateDrawPrompt():

    promptStr = random.choice(situations)

    return ReplacePeopleInSituations(promptStr)
